/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  cdn: [
    {
      type: "category",
      label: "CDN",
      link: {
        type: "generated-index",
        title: "CDN API",
        description:
          "API Access to Musson Industrial's CDN.",
        slug: "/musson-industrial-cdn-api",
      },
      items: require("./docs/api/cdn/sidebar.js"),
    },
  ],

  ignition_modules: [
    {
      type: 'autogenerated',
      dirName: 'ignition-modules'
    }
  ],

};

module.exports = sidebars;
