/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  ignitionModules: [
    {
      type: 'category',
      label: 'Ignition Modules',
      link: {
        // type: 'generated-index'
        type: 'doc',
        id: 'ignition-modules/index'
      },
      items: [
        {
          type: 'category',
          label: 'BarTender Drivers Module',
          link: {
            type: 'doc',
            id: 'ignition-modules/bartender/index'
          },
          items: [
            'ignition-modules/bartender/installation',
            {
              type: 'category',
              label: 'Creating and Configuring Connections',
              link: {
                type: 'doc',
                id: 'ignition-modules/bartender/connections/index'
              },
              items: [
                'ignition-modules/bartender/connections/web-service',
                'ignition-modules/bartender/connections/tcp-socket'             
              ]
            },
            {
              type: 'category',
              label: 'Sending Print Commands',
              link: {
                type: 'doc',
                id: 'ignition-modules/bartender/printing/index'
              },
              items: [
                'ignition-modules/bartender/printing/btxml',
                // 'ignition-modules/bartender/scripting/runBlocking'             
              ]
            },
            // {
            //   type: 'category',
            //   label: 'Working with BTXML',
            //   link: {
            //     type: 'doc',
            //     id: 'ignition-modules/bartender/btxml/root'
            //   },
            //   items: [
            //     // 'ignition-modules/bartender/scripting/runAsync',
            //     // 'ignition-modules/bartender/scripting/runBlocking'             
            //   ]
            // },
            {
              type: 'category',
              label: 'Scripting',
              link: {
                type: 'doc',
                id: 'ignition-modules/bartender/scripting/index'
              },
              items: [
                'ignition-modules/bartender/scripting/runAsync',
                'ignition-modules/bartender/scripting/runBlocking'             
              ]
            }
          ],
        }
      ],
    }
  ]
};

module.exports = sidebars;
