import {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  ignition_modules: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],

};

export default sidebars;